name: test and lint

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
        Scripts: ./.github/workflows/Scripts

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
    - name: Install dotnet-coverage
      run: dotnet tool install -g dotnet-coverage
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

   # - name: Build Coverage Report
   #   run: reportgenerator -reports:"coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
            name: coverage-artifacts
            path: coveragereport/
    - name: Calculate Code Coverage Percentage with PowerShell
      shell: pwsh
      run: ${{ env.Scripts }}/CodeCoverage.ps1
      env:
          COVERAGE_THRESHOLD: $coverageThreshold

  code-format:
    runs-on: ubuntu-latest
      
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format

    - name: Check Code Formatting
      run: dotnet format --severity error --verify-no-changes
